version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPORT=5432
  client:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    depends_on:
      - redis
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    depends_on:
      - api
      - client
    restart: always
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx


     
  
